# Generated by Django 5.2.1 on 2025-07-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
